$PublicDir  = Join-Path $PSScriptRoot 'Public'
$PrivateDir = Join-Path $PSScriptRoot 'Private'

Get-ChildItem -Path $PrivateDir -Filter '*.ps1' -ErrorAction Stop | ForEach-Object {
    . $_.FullName
}
Get-ChildItem -Path $PublicDir -Filter '*.ps1' -ErrorAction Stop | ForEach-Object {
    . $_.FullName
}

Export-ModuleMember -Function @(
    'Get-BobHealth',
    'Get-BobWorkers',
    'Get-BobAgents',
    'Get-BobMachines',
    'Register-BobMachine',
    'Start-BobWorker',
    'Start-BobBuild',
    'Get-BobCapacity',
    'Get-BobJobModel',
    'Test-BobFuelModelCompatible',
    'Test-BobPacketMissingFuel',
    'Resolve-BobGrokCliModel',
    'Select-BobGitWorker',
    'Get-ThisMachineId',
    'Copy-BobProjectSkills',
    'Get-BobBuild',
    'Get-BobBuilds',
    'Send-BobBuildSpec',
    'Stop-BobBuild',
    'Invoke-BobFleetTick',
    'Send-BobPrompt',
    'Get-BobStatus',
    'Get-BobResult',
    'Stop-BobWorker',
    'Export-BobTranscript',
    'Get-BobStallAlerts',
    'Get-BobTrayHover',
    'Get-BobCursorOverageGbp',
    'Get-BobSeatForMachine',
    'Get-BobSeatConfig',
    'Format-BobCursorAccountLabel',
    'Test-BobCursorOverageLabel',
    'Get-BobLiveGrokAgents',
    'Get-BobTrayBarPaint',
    'Get-BobTrayBarFillRgb',
    'Get-BobTrayAlertKind',
    'Get-BobTrayTitle',
    'Get-BobWeeklyRemaining',
    'Get-BobCursorAgentWeeklyRemaining',
    'Get-BobCursorSpendingFromApiFixture',
    'Get-BobTrayTipPlacement',
    'Get-BobFleetRegistry',
    'ConvertTo-BobIrcPoint',
    'ConvertFrom-BobIrcPoint',
    'Read-BobIrcPeer',
    'Write-BobIrcStatus',
    'Import-BobIrcPeerTranscript',
    'Import-BobIrcTrayPull',
    'Request-BobIrcBobiversePull',
    'Sync-BobDigestWebhookAfterBobiversePull',
    'ConvertFrom-BobIrcTrayLine',
    'Get-BobJobRepoStamp',
    'Get-BobIrcShopChannel',
    'Get-BobIrcBuilderChannels',
    'Get-BobWorkerIrcNick',
    'Compact-BobIrcOutbox',
    'Write-BobJobAuditLine',
    'Write-BobJobAuditFromPacket',
    'Invoke-BobGrokTalkTick',
    'Test-BobGrokTalkFuelAllowed',
    'Select-BobGrokTalkFuel',
    'Add-BobGrokTalkCompletion',
    'ConvertTo-BobGrokTalkOutLines'
)
